* 🐕 BARK --- Bug And Report Keeper

BARK monitors a mailbox and converts incoming emails into reports.
Subsequent emails in the same thread can update the status of that
report using predefined trigger keywords. Admins and maintainers can
update reports by writing directly to the monitored inbox, manage
roles, and receive periodic digest emails.

For a more detailed howto, see the [[https://codeberg.org/bzg/bark/src/branch/main/docs/howto.org][BARK project page]].

** Labels and trigger keywords

Subject labels create reports. Replies to these reports can update
them by using trigger keywords such as =applied.=, etc. Trigger keywords
should be placed at the beginning of the line and followed by a
punctuation mark (=.= =,= =;= =:=).

Here is a table of available labels and triggers for this BARK
instance:

| Type         | Subject labels                                  | Acked              | Owned   | Closed               |
|--------------+-------------------------------------------------+--------------------+---------+----------------------|
| bug          | =[BUG]= =[BUG version]=                             | =Approved= =Confirmed= | =Handled= | =Canceled= =Fixed=       |
| patch        | =[PATCH]= =[PATCH n/m]= =[PATCH topic n/m]=           | =Approved= =Reviewed=  | =Handled= | =Canceled= =Applied=     |
| request      | =[POLL]= =[FR]= =[TODO]=                              | =Approved=           | =Handled= | =Canceled= =Done= =Closed= |
|--------------+-------------------------------------------------+--------------------+---------+----------------------|
| announcement | =[ANN]= =[ANNOUNCEMENT]=                            |                    |         | =Canceled=             |
| release      | =[REL]= =[RELEASE]= =[REL version]= =[RELEASE version]= |                    |         | =Canceled=             |
| change       | =[CHG]= =[CHANGE]= =[CHG version]= =[CHANGE version]=   |                    |         | =Canceled=             |

** Priority trigger keywords

On top of trigger keyword to update the status of a report, users can
tell if it is important or urgent. They cannot set the priority
directly: it is computed as the sum of important (+1) and urgent (+2).

** Combining trigger keywords

You can combine several triggers in a single email:

#+begin_example
Confirmed.
Urgent.
Important.
#+end_example
